"""Release authority plus an explicit predecessor-registry compatibility export."""

from .registry_release_registration import RuntimeReleaseBundle, RuntimeReleaseRegistry
from .registry_plugin_registration import RuntimeModulePlugin
from .registry_authoring_inventory_loading import (
    RUNTIME_AUTHORING_INVENTORY_SCHEMA_VERSION,
    RUNTIME_MODULE_REGISTRATION_SCHEMA_VERSION,
    RuntimeAuthoringSourceSet,
    load_runtime_authoring_inventory,
)
from .registry_authoring_release_building import (
    RuntimeReleaseBuildResult,
    build_runtime_release_set,
)
from .registry_authoring_release_submission import (
    RuntimeReleaseRegistrationReport,
    RuntimeReleaseRegistrationStore,
    register_runtime_release_set,
)
from .registry_postgres_persistence import (
    PostgresRuntimeReleaseQueryStore,
    PostgresRuntimeReleaseStore,
    REGISTRY_SCHEMA_RELEASE_ID,
)
from .registry_release_compilation import (
    AgentModuleReleaseCandidate,
    BehaviorPolicyReleaseCandidate,
    CompiledAgentModuleRelease,
    CompiledNonAgentModuleRelease,
    EvaluationPolicyReleaseCandidate,
    ExecutionProfileReleaseSpec,
    ExecutionVariantPolicyReleaseCandidate,
    ExecutionVariantProfileBindingCandidate,
    NonAgentModuleReleaseCandidate,
    RetryPolicyReleaseCandidate,
    WorkflowNodeReleaseCandidate,
    WorkflowReleaseCandidate,
    candidate_admission_intent,
    compile_agent_module_release,
    compile_behavior_policy_release,
    compile_evaluation_policy_release,
    compile_execution_profile_release,
    compile_execution_variant_policy_release,
    compile_non_agent_module_release,
    compile_prompt_bundle_release,
    compile_retry_policy_release,
    compile_workflow_release,
    runtime_owned_policy_schema_assets,
)
from .registry_workflow_registration import (
    WorkflowRuntimeRegistry,
    resolve_registration_reference,
)
from .registry_architecture_registration import (
    RUNTIME_IMPLEMENTATION_BINDING_REGISTRATIONS,
    RUNTIME_LOGICAL_RESPONSIBILITY_REGISTRATIONS,
    RUNTIME_MIGRATION_DEBT_PATHS,
    RUNTIME_REQUIRED_LOGICAL_RESPONSIBILITY_IDS,
    RUNTIME_SOURCE_DIRECTORY_REGISTRATIONS,
    RUNTIME_SOURCE_FILE_REGISTRATIONS,
    RUNTIME_STRUCTURAL_SOURCE_PATHS,
    RuntimeImplementationBindingRegistration,
    RuntimeLogicalResponsibilityRegistration,
    RuntimeSourceDirectoryRegistration,
    RuntimeSourceFileRegistration,
    validate_registry_architecture_registration,
    validate_runtime_architecture_registration,
)

__all__ = [
    "AgentModuleReleaseCandidate",
    "BehaviorPolicyReleaseCandidate",
    "CompiledAgentModuleRelease",
    "CompiledNonAgentModuleRelease",
    "EvaluationPolicyReleaseCandidate",
    "ExecutionProfileReleaseSpec",
    "ExecutionVariantPolicyReleaseCandidate",
    "ExecutionVariantProfileBindingCandidate",
    "NonAgentModuleReleaseCandidate",
    "RUNTIME_IMPLEMENTATION_BINDING_REGISTRATIONS",
    "RUNTIME_LOGICAL_RESPONSIBILITY_REGISTRATIONS",
    "RUNTIME_MIGRATION_DEBT_PATHS",
    "RUNTIME_REQUIRED_LOGICAL_RESPONSIBILITY_IDS",
    "RUNTIME_SOURCE_DIRECTORY_REGISTRATIONS",
    "RUNTIME_SOURCE_FILE_REGISTRATIONS",
    "RUNTIME_STRUCTURAL_SOURCE_PATHS",
    "RuntimeImplementationBindingRegistration",
    "RuntimeLogicalResponsibilityRegistration",
    "RUNTIME_AUTHORING_INVENTORY_SCHEMA_VERSION",
    "RUNTIME_MODULE_REGISTRATION_SCHEMA_VERSION",
    "PostgresRuntimeReleaseStore",
    "PostgresRuntimeReleaseQueryStore",
    "REGISTRY_SCHEMA_RELEASE_ID",
    "RuntimeReleaseBundle",
    "RuntimeModulePlugin",
    "RuntimeAuthoringSourceSet",
    "RuntimeReleaseBuildResult",
    "RuntimeReleaseRegistrationReport",
    "RuntimeReleaseRegistrationStore",
    "RuntimeReleaseRegistry",
    "RuntimeSourceFileRegistration",
    "RuntimeSourceDirectoryRegistration",
    "RetryPolicyReleaseCandidate",
    "WorkflowNodeReleaseCandidate",
    "WorkflowReleaseCandidate",
    "WorkflowRuntimeRegistry",
    "candidate_admission_intent",
    "compile_agent_module_release",
    "compile_behavior_policy_release",
    "compile_evaluation_policy_release",
    "compile_execution_profile_release",
    "compile_execution_variant_policy_release",
    "compile_non_agent_module_release",
    "compile_prompt_bundle_release",
    "compile_retry_policy_release",
    "compile_workflow_release",
    "build_runtime_release_set",
    "load_runtime_authoring_inventory",
    "register_runtime_release_set",
    "resolve_registration_reference",
    "runtime_owned_policy_schema_assets",
    "validate_registry_architecture_registration",
    "validate_runtime_architecture_registration",
]
