"""Code-owned architecture constraints and temporary debt baselines.

The manifest separates the target dependency graph from today's exact debt.
Validators may accept a strict subset of the debt set, but never an addition.
"""

from __future__ import annotations

from types import MappingProxyType


RUNTIME_ALLOWED_DEPENDENCY_TARGETS = MappingProxyType(
    {
        "foundation": frozenset(),
        "registry": frozenset({"foundation"}),
        "invocation": frozenset({"foundation", "registry"}),
        "durability": frozenset({"foundation"}),
        "ledger": frozenset({"foundation"}),
        "execution": frozenset(
            {"foundation", "registry", "invocation", "durability", "ledger"}
        ),
        "inspection": frozenset({"foundation", "registry", "ledger"}),
        "conformance": frozenset(
            {
                "foundation",
                "registry",
                "invocation",
                "durability",
                "ledger",
                "execution",
                "inspection",
                "public_facade",
                "compatibility_facade",
            }
        ),
        "public_facade": frozenset(
            {
                "foundation",
                "registry",
                "invocation",
                "durability",
                "ledger",
                "execution",
                "inspection",
                "compatibility_facade",
            }
        ),
        "compatibility_facade": frozenset(
            {
                "foundation",
                "registry",
                "invocation",
                "durability",
                "ledger",
                "execution",
                "inspection",
            }
        ),
    }
)


RUNTIME_STRUCTURAL_MODULE_OWNERS = MappingProxyType(
    {
        "agent_runtime": "public_facade",
        "agent_runtime.conformance": "conformance",
        "agent_runtime.contracts": "compatibility_facade",
        "agent_runtime.durability": "durability",
        "agent_runtime.execution": "execution",
        "agent_runtime.foundation": "foundation",
        "agent_runtime.inspection": "inspection",
        "agent_runtime.invocation": "invocation",
        "agent_runtime.ledger": "ledger",
        "agent_runtime.registry": "registry",
        "agent_runtime.testing": "public_facade",
    }
)


RUNTIME_MIGRATION_DEBT_OWNERS = MappingProxyType(
    {
        "src/agent_runtime/contracts/execution_operation_definition.py": "execution",
        "src/agent_runtime/contracts/registry_workflow_definition.py": "registry",
        "src/agent_runtime/execution/execution_event_ingestion.py": "execution",
        "src/agent_runtime/execution/execution_operation_authorization.py": "execution",
        "src/agent_runtime/registry/registry_workflow_registration.py": "registry",
    }
)


RUNTIME_MIGRATION_DEBT_HIGH_WATER = frozenset(RUNTIME_MIGRATION_DEBT_OWNERS)


RUNTIME_DEPENDENCY_DEBT_HIGH_WATER = frozenset(
    {
        (
            "src/agent_runtime/contracts/durability_backend_definition.py",
            "agent_runtime.contracts.execution_host_definition",
        ),
        (
            "src/agent_runtime/contracts/durability_execution_definition.py",
            "agent_runtime.contracts.registry_workflow_definition",
        ),
        (
            "src/agent_runtime/contracts/invocation_adapter_definition.py",
            "agent_runtime.contracts.ledger_lineage_definition",
        ),
        (
            "src/agent_runtime/contracts/ledger_lineage_definition.py",
            "agent_runtime.contracts.registry_release_definition",
        ),
        (
            "src/agent_runtime/contracts/ledger_record_definition.py",
            "agent_runtime.contracts.registry_workflow_definition",
        ),
        (
            "src/agent_runtime/durability/durability_temporal_coordination.py",
            "agent_runtime.contracts.registry_release_definition",
        ),
        (
            "src/agent_runtime/durability/durability_temporal_coordination.py",
            "agent_runtime.registry.registry_graph_projection",
        ),
        (
            "src/agent_runtime/durability/durability_temporal_coordination.py",
            "agent_runtime.contracts.execution_host_definition",
        ),
        (
            "src/agent_runtime/durability/durability_temporal_coordination.py",
            "agent_runtime.registry.registry_release_registration",
        ),
        (
            "src/agent_runtime/durability/durability_workflow_coordination.py",
            "agent_runtime.contracts.registry_release_definition",
        ),
        (
            "src/agent_runtime/durability/durability_workflow_coordination.py",
            "agent_runtime.contracts.registry_workflow_definition",
        ),
        (
            "src/agent_runtime/durability/durability_workflow_coordination.py",
            "agent_runtime.registry.registry_graph_projection",
        ),
        (
            "src/agent_runtime/durability/durability_workflow_coordination.py",
            "agent_runtime.contracts.execution_host_definition",
        ),
        (
            "src/agent_runtime/durability/durability_workflow_coordination.py",
            "agent_runtime.registry.registry_release_registration",
        ),
        (
            "src/agent_runtime/invocation/invocation_claude_module_invocation.py",
            "agent_runtime.contracts.ledger_lineage_definition",
        ),
        (
            "src/agent_runtime/invocation/invocation_prompt_assembly.py",
            "agent_runtime.contracts.execution_module_definition",
        ),
        (
            "src/agent_runtime/invocation/invocation_result_assembly.py",
            "agent_runtime.contracts.ledger_lineage_definition",
        ),
        (
            "src/agent_runtime/invocation/invocation_tool_definition.py",
            "agent_runtime.contracts.execution_module_definition",
        ),
        (
            "src/agent_runtime/invocation/invocation_tool_definition.py",
            "agent_runtime.contracts.ledger_lineage_definition",
        ),
        (
            "src/agent_runtime/ledger/ledger_lineage_recording.py",
            "agent_runtime.contracts.execution_module_definition",
        ),
        (
            "src/agent_runtime/ledger/ledger_postgres_persistence.py",
            "agent_runtime.contracts.registry_workflow_definition",
        ),
        (
            "src/agent_runtime/ledger/ledger_record_persistence.py",
            "agent_runtime.contracts.registry_workflow_definition",
        ),
        (
            "src/agent_runtime/ledger/ledger_workflow_execution_recording.py",
            "agent_runtime.contracts.registry_workflow_definition",
        ),
        (
            "src/agent_runtime/ledger/ledger_workflow_module_recording.py",
            "agent_runtime.contracts.execution_module_definition",
        ),
        (
            "src/agent_runtime/ledger/ledger_workflow_module_recording.py",
            "agent_runtime.contracts.invocation_adapter_definition",
        ),
        (
            "src/agent_runtime/ledger/ledger_workflow_module_recording.py",
            "agent_runtime.contracts.registry_release_definition",
        ),
        (
            "src/agent_runtime/ledger/ledger_workflow_module_recording.py",
            "agent_runtime.invocation.invocation_tool_definition",
        ),
        (
            "src/agent_runtime/registry/registry_graph_projection.py",
            "agent_runtime.contracts",
        ),
        (
            "src/agent_runtime/registry/registry_graph_projection.py",
            "agent_runtime.contracts.durability_execution_definition",
        ),
        (
            "src/agent_runtime/registry/registry_plugin_registration.py",
            "agent_runtime.contracts",
        ),
        (
            "src/agent_runtime/registry/registry_plugin_registration.py",
            "agent_runtime.contracts.durability_execution_definition",
        ),
        (
            "src/agent_runtime/registry/registry_workflow_registration.py",
            "agent_runtime.contracts",
        ),
    }
)


RUNTIME_PUBLIC_SURFACE_MANIFEST = MappingProxyType(
    {
        "agent_runtime": (
            "AgenticWorkflowConformancePackage",
            "AgentExecutionAdapterDescriptor",
            "AgentExecutionAdapterRegistry",
            "AttemptToolReconciliationRequiredError",
            "AgentExecutionFailure",
            "AgentExecutionResult",
            "AgentRuntimeProductHostApi",
            "AuthorizationAdapter",
            "AuthorizationEffect",
            "AuthorizedAgentExecutionAdapter",
            "AuthorizedAgentExecutionHost",
            "AuthorizedAgentExecutionRequest",
            "AuthorizedOperationReceipt",
            "BoundOperationAuthorization",
            "ModuleInputProjection",
            "ModuleInputProjectionContract",
            "ConformanceContractBinding",
            "ConformanceContractKind",
            "CellModuleActivityBridge",
            "DomainRuntimePlugin",
            "DynamicInputBinding",
            "DurableExecutionCoordinator",
            "DurableExecutionProgress",
            "DurableExecutionStopReason",
            "ExecutionProfileRelease",
            "ExecutionAuthorizationBinding",
            "ExecutionAuthorizationAdmissionResult",
            "ExecutionAuthorizationContextBinding",
            "ExecutionAuthorizationContextEnvelope",
            "ExecutionAuthorizationContextState",
            "ExecutionAuthorizationController",
            "ExecutionAuthorizationFence",
            "ExecutionAuthorizationFenceState",
            "ExecutionAuthorizationStatus",
            "ExecutionAuthorizationStatusEvidence",
            "ExecutionControlFenceStatus",
            "ExecutionSnapshotToken",
            "ExternalActionAuthorizationEvidence",
            "AuthorizedExternalEvent",
            "DurableCursorExternalEvent",
            "GatewayAuthorizationObservation",
            "GatewayDecisionEffect",
            "ExternalEventAcknowledgement",
            "ExternalEventApplicationRecord",
            "ExternalEventIngressRecord",
            "ExternalEventIngressRequest",
            "InMemoryModuleExecutionLedger",
            "InMemoryAuthorizationLedger",
            "InMemoryExecutionAuthorizationLedger",
            "InMemoryExternalEventIngress",
            "ModuleEntryPolicy",
            "ModuleExecutionAuthority",
            "ModuleExecutionPurpose",
            "ModuleExecutionRequest",
            "ModuleInputBinding",
            "ModuleKind",
            "PromptComponentKind",
            "PromptComponentRelease",
            "ModuleOutputBinding",
            "ModuleOutputResolutionRecord",
            "ModuleRunResult",
            "ModuleUsageObservation",
            "ModuleVariantRequest",
            "WorkflowModuleExecutionRequest",
            "OutputResolutionPolicy",
            "OutputSubmission",
            "OperationAuthorizationRequest",
            "OperationAuthorizationQuery",
            "OperationAuthorizationResolution",
            "OperationAuthorizationResolutionRecord",
            "OperationGrantBindingRecord",
            "PromptBundleRelease",
            "ProductOperationAuthorizationResult",
            "ProductOperationDecision",
            "ProductAuthorizationContextStatus",
            "ProductAuthorizationContextClient",
            "ProductOperationAuthorizationClient",
            "ProtectedOperationIntent",
            "ProviderOperationIntent",
            "BehaviorPolicyRelease",
            "EvaluationPolicyRelease",
            "ExecutionVariantPolicyRelease",
            "ReleaseAdmissionIntent",
            "ReleaseAdmissionRecord",
            "ReleaseAdmissionState",
            "ReleaseMember",
            "ReleaseSubjectKind",
            "RetryPolicyRelease",
            "RuntimeModulePlugin",
            "RuntimeModuleReleaseClient",
            "RuntimeModuleRelease",
            "SchemaAssetRelease",
            "RuntimeProtectedOperationClient",
            "RuntimeAuthorizationCoordinator",
            "RuntimeCancellationRequest",
            "RuntimeExecutionHandle",
            "RuntimeExecutionStatus",
            "RuntimeExecutionView",
            "RuntimeReconciliationResult",
            "RuntimeWorkflowStartRequest",
            "RuntimeReleaseBundle",
            "RuntimeReleaseRegistry",
            "TrustedRequestContext",
            "WorkflowAdmissionState",
            "WorkflowManagementLifecycle",
            "WorkflowRuntimeRegistration",
            "WorkflowEdge",
            "WorkflowExecutionArtifactHost",
            "WorkflowExecutionLedgerBinding",
            "WorkflowExecutionLedgerRecorder",
            "WorkflowNodeBinding",
            "WorkflowParallelGroupBinding",
            "WorkflowParallelJoinPolicy",
            "WorkflowRelease",
            "WorkflowRuntimeRegistry",
            "aggregate_model_usage",
            "isolated_execution_scope_id",
            "register_runtime_plugin",
            "run_module",
            "run_workflow_module",
            "validate_domain_runtime_manifest",
        ),
        "agent_runtime.conformance": (
            "build_downstream_consumer_manifest",
            "validate_downstream_consumer_manifest",
            "validate_downstream_consumer_retirement_readiness",
            "validate_runtime_architecture",
        ),
        "agent_runtime.contracts": (
            "AgenticWorkflowConformancePackage",
            "AuthorizationEffect",
            "AdapterContextRequest",
            "AdapterContextResult",
            "AuthorizedAgentExecutionAdapter",
            "AuthorizedAgentExecutionHost",
            "AuthorizedAgentExecutionRequest",
            "AuthorizedOperationReceipt",
            "AgentExecutionAdapterDescriptor",
            "AgentExecutionFailure",
            "AgentExecutionResult",
            "AuthorizedExecutionInput",
            "BackendEvent",
            "BackendExecutionRef",
            "CellModuleDispatchContext",
            "ModuleInputProjection",
            "ModuleInputProjectionContract",
            "ModuleInvocationRequest",
            "ModuleInvocationResult",
            "DomainDriver",
            "ConformanceContractBinding",
            "ConformanceContractKind",
            "DurableBackendAdapter",
            "DynamicInputBinding",
            "ExecutionSnapshot",
            "ExecutionProfileRelease",
            "ExecutionAuthorizationBinding",
            "ExecutionAuthorizationContextBinding",
            "ExecutionAuthorizationContextEnvelope",
            "ExecutionAuthorizationContextState",
            "ExecutionAuthorizationFence",
            "ExecutionAuthorizationFenceState",
            "ExecutionAuthorizationStatus",
            "ExecutionAuthorizationStatusEvidence",
            "ExecutionControlFenceStatus",
            "ExecutionOutputRegistrationRequest",
            "ExecutionOutputRegistrationResult",
            "DurableCursorExternalEvent",
            "PredecessorWorkflowExternalEvent",
            "ExternalEventAcknowledgement",
            "ExternalEventIngressRequest",
            "GatewayAuthorizationObservation",
            "GatewayDecisionEffect",
            "OperationAuthorizationQuery",
            "ResolvedArtifactRef",
            "ResolvedExecutionProfile",
            "REQUIRED_CONFORMANCE_CONTRACT_KINDS",
            "RuntimeExecutionServices",
            "ModuleEntryPolicy",
            "ModuleAttemptRecord",
            "ModuleAttemptStartedRecord",
            "ModuleExecutionVariantRecord",
            "ModuleOutputResolutionRecord",
            "ModuleExecutionPurpose",
            "ModuleKind",
            "ModuleRunRecord",
            "ModuleToolCallObservation",
            "ModuleUsageObservation",
            "ModuleExecutionLedger",
            "ModuleFailureDetailBinding",
            "ModuleInputBinding",
            "ModuleOutputBinding",
            "PromptComponentKind",
            "PromptComponentRelease",
            "OperationAuthorizationRequest",
            "OperationAuthorizationResolution",
            "OperationAuthorizationResolutionRecord",
            "OperationGrantBindingRecord",
            "OutputResolutionPolicy",
            "OutputSubmission",
            "PromptBundleRelease",
            "ProductOperationAuthorizationResult",
            "ProductAuthorizationContextStatus",
            "ProductOperationDecision",
            "ProtectedOperationIntent",
            "ProviderOperationIntent",
            "BehaviorPolicyRelease",
            "EvaluationPolicyRelease",
            "ExecutionVariantPolicyRelease",
            "ReleaseAdmissionIntent",
            "ReleaseAdmissionRecord",
            "ReleaseAdmissionState",
            "ReleaseMember",
            "ReleaseSubjectKind",
            "RetryPolicyRelease",
            "RuntimeModuleRelease",
            "SchemaAssetRelease",
            "RuntimeCancellationRequest",
            "RuntimeWorkflowStartRequest",
            "ModuleDispatchRequest",
            "ModuleOutcome",
            "ModuleOutcomeDisposition",
            "ModuleRunCreationRequest",
            "ModuleRunCreationResult",
            "WorkflowAdmissionState",
            "WorkflowEdge",
            "WorkflowManagementLifecycle",
            "WorkflowNodeKind",
            "WorkflowNodeBinding",
            "WorkflowParallelGroupBinding",
            "WorkflowParallelJoinPolicy",
            "WorkflowRelease",
            "WorkflowRuntimeRegistration",
            "validate_capability_id",
            "validate_domain_runtime_manifest",
            "validate_usd_amount",
            "format_usd_amount",
            "validate_id",
            "validate_int",
            "validate_opaque_ref",
            "validate_runtime_ref",
            "validate_sha256",
        ),
        "agent_runtime.durability": (),
        "agent_runtime.execution": (
            "AgentExecutionAdapterRegistry",
            "AttemptToolReconciliationRequiredError",
            "InMemoryCellArtifactStore",
            "ModuleExecutionAuthority",
            "ModuleExecutionRequest",
            "ModuleInputBinding",
            "ModuleOutputBinding",
            "ModuleRunResult",
            "ModuleVariantRequest",
            "WorkflowModuleExecutionRequest",
            "isolated_execution_scope_id",
            "run_module",
            "run_workflow_module",
        ),
        "agent_runtime.foundation": (
            "format_utc_timestamp",
            "format_usd_amount",
            "iter_json_schema_nodes",
            "parse_utc_timestamp",
            "resolve_local_schema_reference",
            "strict_output_schema_projection",
            "transform_json_schema_nodes",
            "validate_bool",
            "validate_enum_string",
            "validate_exact_record_instance",
            "validate_exact_record_tuple",
            "validate_id",
            "validate_int",
            "validate_json_document_against_schema",
            "validate_json_schema_document",
            "validate_opaque_ref",
            "validate_pattern_string",
            "validate_sha256",
            "validate_snake_case_name",
            "validate_string_tuple",
            "validate_token",
            "validate_utc_timestamp",
            "validate_usd_amount",
        ),
        "agent_runtime.inspection": (
            "ARCHITECTURE_PROJECTION_SCHEMA_VERSION",
            "build_runtime_architecture_projection",
            "build_runtime_execution_inspection",
            "build_runtime_release_inventory",
            "build_workflow_review_bundle",
            "LiveInspectionAssembly",
            "LiveInspectionAuthorizer",
            "LiveWorkflowInspectorApplication",
            "load_live_inspection_application",
            "PostgresWorkflowInspectionRepository",
            "RELEASE_INVENTORY_SCHEMA_VERSION",
            "ReleaseInventorySelection",
            "render_runtime_architecture_markdown",
            "render_runtime_release_markdown",
            "render_workflow_review_html",
            "ReviewContent",
            "serve_live_inspector",
            "validate_workflow_review_bundle",
            "WORKFLOW_REVIEW_BUNDLE_SCHEMA_VERSION",
            "WorkflowInspectionRepository",
        ),
        "agent_runtime.invocation": (),
        "agent_runtime.ledger": (
            "aggregate_model_usage",
            "InMemoryModuleExecutionLedger",
            "InMemoryRuntimeExecutionRecordStore",
            "PostgresRuntimeExecutionRecordStore",
            "PostgresRuntimeExecutionQueryStore",
            "RuntimeExecutionContent",
            "RuntimeExecutionContentReader",
            "RuntimeExecutionContentStore",
            "RuntimeExecutionDescriptor",
            "RuntimeExecutionPageCursor",
            "RuntimeExecutionRecordStore",
            "WorkflowExecutionArtifactHost",
            "WorkflowExecutionLedgerBinding",
            "WorkflowExecutionLedgerRecorder",
            "WorkflowModuleLedgerBinding",
            "WorkflowModuleLedgerRecorder",
            "deserialize_runtime_batch",
            "deserialize_runtime_record",
            "postgres_execution_ledger_ddl",
            "serialize_runtime_batch",
            "record_execution_content",
        ),
        "agent_runtime.registry": (
            "AgentModuleReleaseCandidate",
            "BehaviorPolicyReleaseCandidate",
            "CompiledAgentModuleRelease",
            "CompiledNonAgentModuleRelease",
            "EvaluationPolicyReleaseCandidate",
            "ExecutionProfileReleaseSpec",
            "ExecutionVariantPolicyReleaseCandidate",
            "ExecutionVariantProfileBindingCandidate",
            "NonAgentModuleReleaseCandidate",
            "RUNTIME_IMPLEMENTATION_BINDING_REGISTRATIONS",
            "RUNTIME_LOGICAL_RESPONSIBILITY_REGISTRATIONS",
            "RUNTIME_MIGRATION_DEBT_PATHS",
            "RUNTIME_REQUIRED_LOGICAL_RESPONSIBILITY_IDS",
            "RUNTIME_SOURCE_DIRECTORY_REGISTRATIONS",
            "RUNTIME_SOURCE_FILE_REGISTRATIONS",
            "RUNTIME_STRUCTURAL_SOURCE_PATHS",
            "RuntimeImplementationBindingRegistration",
            "RuntimeLogicalResponsibilityRegistration",
            "RUNTIME_AUTHORING_INVENTORY_SCHEMA_VERSION",
            "RUNTIME_MODULE_REGISTRATION_SCHEMA_VERSION",
            "PostgresRuntimeReleaseStore",
            "PostgresRuntimeReleaseQueryStore",
            "REGISTRY_SCHEMA_RELEASE_ID",
            "RuntimeReleaseBundle",
            "RuntimeModulePlugin",
            "RuntimeAuthoringSourceSet",
            "RuntimeReleaseBuildResult",
            "RuntimeReleaseRegistrationReport",
            "RuntimeReleaseRegistrationStore",
            "RuntimeReleaseRegistry",
            "RuntimeSourceFileRegistration",
            "RuntimeSourceDirectoryRegistration",
            "RetryPolicyReleaseCandidate",
            "WorkflowNodeReleaseCandidate",
            "WorkflowReleaseCandidate",
            "WorkflowRuntimeRegistry",
            "candidate_admission_intent",
            "compile_agent_module_release",
            "compile_behavior_policy_release",
            "compile_evaluation_policy_release",
            "compile_execution_profile_release",
            "compile_execution_variant_policy_release",
            "compile_non_agent_module_release",
            "compile_prompt_bundle_release",
            "compile_retry_policy_release",
            "compile_workflow_release",
            "build_runtime_release_set",
            "load_runtime_authoring_inventory",
            "register_runtime_release_set",
            "resolve_registration_reference",
            "runtime_owned_policy_schema_assets",
            "validate_registry_architecture_registration",
            "validate_runtime_architecture_registration",
        ),
        "agent_runtime.testing": (
            "AdapterFactory",
            "AuthorityFactory",
            "RegisteredModuleEvaluation",
            "run_registered_inline_module_evaluation",
        ),
    }
)


__all__ = [
    "RUNTIME_ALLOWED_DEPENDENCY_TARGETS",
    "RUNTIME_DEPENDENCY_DEBT_HIGH_WATER",
    "RUNTIME_MIGRATION_DEBT_HIGH_WATER",
    "RUNTIME_MIGRATION_DEBT_OWNERS",
    "RUNTIME_PUBLIC_SURFACE_MANIFEST",
    "RUNTIME_STRUCTURAL_MODULE_OWNERS",
]
