"""Public Runtime surface with explicit predecessor compatibility exports.

New integrations use immutable Release and Module execution contracts. Legacy
workflow-registration and operation-authorization exports remain only until
the code-owned migration-debt set is retired.
"""

from .contracts import (
    BehaviorPolicyRelease,
    AgenticWorkflowConformancePackage,
    ModuleInputProjection,
    ModuleInputProjectionContract,
    ConformanceContractBinding,
    ConformanceContractKind,
    DynamicInputBinding,
    WorkflowManagementLifecycle,
    WorkflowAdmissionState,
    WorkflowRuntimeRegistration,
    validate_domain_runtime_manifest,
    ExecutionProfileRelease,
    EvaluationPolicyRelease,
    ExecutionVariantPolicyRelease,
    PromptComponentKind,
    PromptComponentRelease,
    ModuleEntryPolicy,
    ModuleExecutionPurpose,
    ModuleKind,
    ModuleOutputResolutionRecord,
    OutputResolutionPolicy,
    PromptBundleRelease,
    ReleaseAdmissionIntent,
    ReleaseAdmissionRecord,
    ReleaseAdmissionState,
    ReleaseMember,
    ReleaseSubjectKind,
    RetryPolicyRelease,
    RuntimeModuleRelease,
    SchemaAssetRelease,
    WorkflowEdge,
    WorkflowNodeBinding,
    WorkflowParallelGroupBinding,
    WorkflowParallelJoinPolicy,
    WorkflowRelease,
    DurableCursorExternalEvent,
    AuthorizationEffect,
    ExecutionAuthorizationBinding,
    ExecutionAuthorizationContextBinding,
    ExecutionAuthorizationContextEnvelope,
    ExecutionAuthorizationContextState,
    ExecutionAuthorizationFence,
    ExecutionAuthorizationFenceState,
    ExecutionAuthorizationStatus,
    ExecutionAuthorizationStatusEvidence,
    ExecutionControlFenceStatus,
    GatewayAuthorizationObservation,
    GatewayDecisionEffect,
    OperationAuthorizationRequest,
    OperationAuthorizationQuery,
    OperationAuthorizationResolution,
    OperationAuthorizationResolutionRecord,
    OperationGrantBindingRecord,
    ProductOperationAuthorizationResult,
    ProductOperationDecision,
    ProductAuthorizationContextStatus,
    ProtectedOperationIntent,
    ProviderOperationIntent,
)
from .execution.execution_operation_authorization import (
    AuthorizationAdapter,
    BoundOperationAuthorization,
    InMemoryAuthorizationLedger,
    RuntimeAuthorizationCoordinator,
)
from .execution.execution_authorization_coordination import (
    ExecutionAuthorizationAdmissionResult,
    ExecutionAuthorizationController,
    InMemoryExecutionAuthorizationLedger,
)
from .durability.durability_workflow_coordination import (
    CellModuleActivityBridge,
    DurableExecutionCoordinator,
    DurableExecutionProgress,
    DurableExecutionStopReason,
)
from .execution.execution_authorization_resolution import (
    ProductAuthorizationContextClient,
    ProductOperationAuthorizationClient,
)
from .contracts.invocation_adapter_definition import (
    AuthorizedAgentExecutionAdapter,
    AuthorizedAgentExecutionHost,
    AuthorizedAgentExecutionRequest,
    AuthorizedOperationReceipt,
    AgentExecutionAdapterDescriptor,
    AgentExecutionFailure,
    AgentExecutionResult,
    OutputSubmission,
)
from .execution.execution_operation_resolution import RuntimeProtectedOperationClient
from .execution.execution_event_ingestion import (
    ExternalActionAuthorizationEvidence,
    ExternalEvent as AuthorizedExternalEvent,
    ExternalEventApplicationRecord,
    ExternalEventIngressRecord,
    ExecutionSnapshotToken,
    InMemoryExternalEventIngress,
    TrustedRequestContext,
)
from .contracts.execution_event_definition import (
    ExternalEventAcknowledgement,
    ExternalEventIngressRequest,
)
from .ledger.ledger_lineage_recording import InMemoryModuleExecutionLedger
from .contracts.execution_module_definition import (
    ModuleExecutionRequest,
    ModuleInputBinding,
    ModuleOutputBinding,
    ModuleRunResult,
    ModuleVariantRequest,
    WorkflowModuleExecutionRequest,
)
from .execution.execution_module_invocation import (
    AgentExecutionAdapterRegistry,
    AttemptToolReconciliationRequiredError,
    ModuleExecutionAuthority,
    isolated_execution_scope_id,
    run_module,
    run_workflow_module,
)
from .contracts.ledger_lineage_definition import ModuleUsageObservation
from .registry.registry_release_retrieval import RuntimeModuleReleaseClient
from .contracts.execution_host_definition import (
    AgentRuntimeProductHostApi,
    RuntimeCancellationRequest,
    RuntimeExecutionHandle,
    RuntimeExecutionStatus,
    RuntimeExecutionView,
    RuntimeReconciliationResult,
    RuntimeWorkflowStartRequest,
)
from .registry.registry_plugin_registration import (
    DomainRuntimePlugin,
    RuntimeModulePlugin,
    register_runtime_plugin,
)
from .registry.registry_release_registration import (
    RuntimeReleaseBundle,
    RuntimeReleaseRegistry,
)
from .registry.registry_workflow_registration import WorkflowRuntimeRegistry
from .ledger.ledger_usage_aggregation import aggregate_model_usage
from .ledger.ledger_workflow_execution_recording import (
    WorkflowExecutionArtifactHost,
    WorkflowExecutionLedgerBinding,
    WorkflowExecutionLedgerRecorder,
)

__all__ = [
    "AgenticWorkflowConformancePackage",
    "AgentExecutionAdapterDescriptor",
    "AgentExecutionAdapterRegistry",
    "AttemptToolReconciliationRequiredError",
    "AgentExecutionFailure",
    "AgentExecutionResult",
    "AgentRuntimeProductHostApi",
    "AuthorizationAdapter",
    "AuthorizationEffect",
    "AuthorizedAgentExecutionAdapter",
    "AuthorizedAgentExecutionHost",
    "AuthorizedAgentExecutionRequest",
    "AuthorizedOperationReceipt",
    "BoundOperationAuthorization",
    "ModuleInputProjection",
    "ModuleInputProjectionContract",
    "ConformanceContractBinding",
    "ConformanceContractKind",
    "CellModuleActivityBridge",
    "DomainRuntimePlugin",
    "DynamicInputBinding",
    "DurableExecutionCoordinator",
    "DurableExecutionProgress",
    "DurableExecutionStopReason",
    "ExecutionProfileRelease",
    "ExecutionAuthorizationBinding",
    "ExecutionAuthorizationAdmissionResult",
    "ExecutionAuthorizationContextBinding",
    "ExecutionAuthorizationContextEnvelope",
    "ExecutionAuthorizationContextState",
    "ExecutionAuthorizationController",
    "ExecutionAuthorizationFence",
    "ExecutionAuthorizationFenceState",
    "ExecutionAuthorizationStatus",
    "ExecutionAuthorizationStatusEvidence",
    "ExecutionControlFenceStatus",
    "ExecutionSnapshotToken",
    "ExternalActionAuthorizationEvidence",
    "AuthorizedExternalEvent",
    "DurableCursorExternalEvent",
    "GatewayAuthorizationObservation",
    "GatewayDecisionEffect",
    "ExternalEventAcknowledgement",
    "ExternalEventApplicationRecord",
    "ExternalEventIngressRecord",
    "ExternalEventIngressRequest",
    "InMemoryModuleExecutionLedger",
    "InMemoryAuthorizationLedger",
    "InMemoryExecutionAuthorizationLedger",
    "InMemoryExternalEventIngress",
    "ModuleEntryPolicy",
    "ModuleExecutionAuthority",
    "ModuleExecutionPurpose",
    "ModuleExecutionRequest",
    "ModuleInputBinding",
    "ModuleKind",
    "PromptComponentKind",
    "PromptComponentRelease",
    "ModuleOutputBinding",
    "ModuleOutputResolutionRecord",
    "ModuleRunResult",
    "ModuleUsageObservation",
    "ModuleVariantRequest",
    "WorkflowModuleExecutionRequest",
    "OutputResolutionPolicy",
    "OutputSubmission",
    "OperationAuthorizationRequest",
    "OperationAuthorizationQuery",
    "OperationAuthorizationResolution",
    "OperationAuthorizationResolutionRecord",
    "OperationGrantBindingRecord",
    "PromptBundleRelease",
    "ProductOperationAuthorizationResult",
    "ProductOperationDecision",
    "ProductAuthorizationContextStatus",
    "ProductAuthorizationContextClient",
    "ProductOperationAuthorizationClient",
    "ProtectedOperationIntent",
    "ProviderOperationIntent",
    "BehaviorPolicyRelease",
    "EvaluationPolicyRelease",
    "ExecutionVariantPolicyRelease",
    "ReleaseAdmissionIntent",
    "ReleaseAdmissionRecord",
    "ReleaseAdmissionState",
    "ReleaseMember",
    "ReleaseSubjectKind",
    "RetryPolicyRelease",
    "RuntimeModulePlugin",
    "RuntimeModuleReleaseClient",
    "RuntimeModuleRelease",
    "SchemaAssetRelease",
    "RuntimeProtectedOperationClient",
    "RuntimeAuthorizationCoordinator",
    "RuntimeCancellationRequest",
    "RuntimeExecutionHandle",
    "RuntimeExecutionStatus",
    "RuntimeExecutionView",
    "RuntimeReconciliationResult",
    "RuntimeWorkflowStartRequest",
    "RuntimeReleaseBundle",
    "RuntimeReleaseRegistry",
    "TrustedRequestContext",
    "WorkflowAdmissionState",
    "WorkflowManagementLifecycle",
    "WorkflowRuntimeRegistration",
    "WorkflowEdge",
    "WorkflowExecutionArtifactHost",
    "WorkflowExecutionLedgerBinding",
    "WorkflowExecutionLedgerRecorder",
    "WorkflowNodeBinding",
    "WorkflowParallelGroupBinding",
    "WorkflowParallelJoinPolicy",
    "WorkflowRelease",
    "WorkflowRuntimeRegistry",
    "aggregate_model_usage",
    "isolated_execution_scope_id",
    "register_runtime_plugin",
    "run_module",
    "run_workflow_module",
    "validate_domain_runtime_manifest",
]
